/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bibliotech.bibliotech;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author unity
 */
public class UsuarioTela extends javax.swing.JFrame {
    /**
     * Creates new form UsuarioTela
     */
    public UsuarioTela() {
        super ("Usuario");
        initComponents();
        buscarUsuarios();
        setLocationRelativeTo(null); 
    }
        private void buscarUsuarios (){
    try{
        DAO dao = new DAO();
        Usuario [] usuario = dao.obterUsuarios();
        usuariosComboBox.setModel(new DefaultComboBoxModel<>(usuario));
    }
        catch (Exception e){
        JOptionPane.showMessageDialog(null, "Usuário não listado, tente novamente mais tarde.");
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        novoUsuarioButton = new javax.swing.JButton();
        atualizarUsuarioButton = new javax.swing.JButton();
        removerUsuarioButton = new javax.swing.JButton();
        cancelarUsuarioButton = new javax.swing.JButton();
        usuariosComboBox = new javax.swing.JComboBox<>();
        usuarioTextField = new javax.swing.JTextField();
        cod_pessoaTextField = new javax.swing.JTextField();
        senhaUsuarioTextField = new javax.swing.JTextField();
        tipoUsuarioTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        novoUsuarioButton.setText("Novo");
        novoUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoUsuarioButtonActionPerformed(evt);
            }
        });

        atualizarUsuarioButton.setText("Atualizar");
        atualizarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarUsuarioButtonActionPerformed(evt);
            }
        });

        removerUsuarioButton.setText("Remover");
        removerUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUsuarioButtonActionPerformed(evt);
            }
        });

        cancelarUsuarioButton.setText("Cancelar");
        cancelarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUsuarioButtonActionPerformed(evt);
            }
        });

        usuariosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosComboBoxActionPerformed(evt);
            }
        });

        usuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario:"));
        usuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextFieldActionPerformed(evt);
            }
        });

        cod_pessoaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Cod_pessoa:"));
        cod_pessoaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_pessoaTextFieldActionPerformed(evt);
            }
        });

        senhaUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha:"));
        senhaUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaUsuarioTextFieldActionPerformed(evt);
            }
        });

        tipoUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo:"));
        tipoUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUsuarioTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senhaUsuarioTextField)
                    .addComponent(usuariosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(novoUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarUsuarioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cod_pessoaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoUsuarioTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(usuariosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cod_pessoaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoUsuarioButton)
                    .addComponent(atualizarUsuarioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerUsuarioButton)
                    .addComponent(cancelarUsuarioButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUsuarioButtonActionPerformed
        UsuarioTela dt = new UsuarioTela();
        dt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarUsuarioButtonActionPerformed

    private void usuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextFieldActionPerformed

    private void cod_pessoaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_pessoaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_pessoaTextFieldActionPerformed

    private void usuariosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosComboBoxActionPerformed
        Usuario usuario = (Usuario) usuariosComboBox.getSelectedItem();
        cod_pessoaTextField.setText(Integer.toString(usuario.getCod_pessoa()));
        usuarioTextField.setText(usuario.getNome());
        senhaUsuarioTextField.setText(usuario.getSenha());
        tipoUsuarioTextField.setText(usuario.getTipo());
    }//GEN-LAST:event_usuariosComboBoxActionPerformed

    private void senhaUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaUsuarioTextFieldActionPerformed

    private void tipoUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUsuarioTextFieldActionPerformed

    private void novoUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoUsuarioButtonActionPerformed
        String nome = usuarioTextField.getText();
        String senha = senhaUsuarioTextField.getText();
        String tipo = tipoUsuarioTextField.getText(); 
        if (nome == null || nome.length() == 0 ||
            senha == null || senha.length() == 0 ||
            tipo == null || tipo.length() == 0) {
        JOptionPane.showMessageDialog (null, "Preencha os dados do usuario");
            }
        else{
    try{
        int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro do novo usuario?");
        if (escolha == JOptionPane.YES_OPTION){
        }
        Usuario usuario = new Usuario (nome, senha, tipo);   
        DAO dao = new DAO();
        dao.inserirUsuarios(usuario);
        JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso");
        buscarUsuarios();
        usuarioTextField.setText("");
        senhaUsuarioTextField.setText("");
        tipoUsuarioTextField.setText("");
            }       
        catch (Exception e){
        JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
        e.printStackTrace();
            }
        } 
    }//GEN-LAST:event_novoUsuarioButtonActionPerformed

    private void atualizarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarUsuarioButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Atualizar usuario?");
        if (escolha == JOptionPane.YES_OPTION){
    try{
        int cod_pessoa = Integer.parseInt (cod_pessoaTextField.getText());
        String nome = usuarioTextField.getText();
        String senha = senhaUsuarioTextField.getText();
        String tipo = tipoUsuarioTextField.getText();

        Usuario usuario = new Usuario (nome, senha, tipo);
        DAO dao = new DAO();
        dao.atualizarUsuarios(usuario);
        JOptionPane.showMessageDialog(null, "Usuario atualizado com sucesso");
        buscarUsuarios();
        cod_pessoaTextField.setText("");
        usuarioTextField.setText("");
        senhaUsuarioTextField.setText("");
        tipoUsuarioTextField.setText("");
    }
        catch (Exception e){
        JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
        e.printStackTrace();
            }
        }

    }//GEN-LAST:event_atualizarUsuarioButtonActionPerformed

    private void removerUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUsuarioButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Remover usuário?");
        if (escolha == JOptionPane.YES_OPTION){
        try{
        int cod_pessoa = Integer.parseInt (cod_pessoaTextField.getText());
        Usuario usuario = new Usuario (cod_pessoa);
        DAO dao = new DAO();
        dao.removerUsuarios(usuario);
        JOptionPane.showMessageDialog(null, "Usuario removido com sucesso!");
        buscarUsuarios();
        usuarioTextField.setText("");
        senhaUsuarioTextField.setText("");
        tipoUsuarioTextField.setText("");
        cod_pessoaTextField.setText("");
        }
        catch (Exception e){
        JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
        e.printStackTrace();
            }
        }
    }//GEN-LAST:event_removerUsuarioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarUsuarioButton;
    private javax.swing.JButton cancelarUsuarioButton;
    private javax.swing.JTextField cod_pessoaTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton novoUsuarioButton;
    private javax.swing.JButton removerUsuarioButton;
    private javax.swing.JTextField senhaUsuarioTextField;
    private javax.swing.JTextField tipoUsuarioTextField;
    private javax.swing.JTextField usuarioTextField;
    private javax.swing.JComboBox<Usuario> usuariosComboBox;
    // End of variables declaration//GEN-END:variables
}
